indentation: 2
opt_in_rules:
  - force_unwrapping
  - closure_spacing
  - unneeded_parentheses_in_closure_argument

included:
  - PlatformTests
  - DomainTests
  - WeatherForecastTests

Excluded:
  - WeatherForecast/AppDelegate.swift
  - WeatherForecastTests/GeneratedMocks.swift
  - DomainTests/GeneratedMocks.swift
  - PlatformTests/GeneratedMocks.swift

function_parameter_count: 
    warning: 10
    error: 15
force_cast: warning
force_try: warning
identifier_name:
  excluded:
    - id
    - to
cyclomatic_complexity:
    ignores_case_statements: true
line_length:
    warning: 200
    error: 300
function_body_length:
    warning: 300
    error: 400
type_body_length:
    warning: 400
    error: 500
file_length:
    warning: 600
    error: 1200
large_tuple:
    warning: 3
    error: 6
